const requirementData = [
    {
        'id' : '1',
        'entityName' : "Apollo Hospital",
        'requirementName' : "Oxygen",
        'primaryContact' : '+91 XXXXXXXXXX',
        'secondaryContact' : '+91 XXXXXXXXXX',
        'location' : "Jaipur, Rajasthan",
        'verified' : true,
    },
    {
        'id' : '2',
        'entityName' : "Apollo Hospital",
        'requirementName' : "Oxygen",
        'primaryContact' : '+91 XXXXXXXXXX',
        'secondaryContact' : '+91 XXXXXXXXXX',
        'location' : "Jaipur, Rajasthan",
        'verified' : false,
    },
    {
        'id' : '3',
        'entityName' : "Apollo Hospital",
        'requirementName' : "Oxygen",
        'primaryContact' : '+91 XXXXXXXXXX',
        'secondaryContact' : '+91 XXXXXXXXXX',
        'location' : "Jaipur, Rajasthan",
        'verified' : true, 
    },
    {
        'id' : '4',
        'entityName' : "Apollo Hospital",
        'requirementName' : "Oxygen",
        'primaryContact' : '+91 XXXXXXXXXX',
        'secondaryContact' : '+91 XXXXXXXXXX',
        'location' : "Jaipur, Rajasthan",
        'verified' : true, 
    },
    {
        'id' : '5',
        'entityName' : "Apollo Hospital",
        'requirementName' : "Oxygen",
        'primaryContact' : '+91 XXXXXXXXXX',
        'secondaryContact' : '+91 XXXXXXXXXX',
        'location' : "Jaipur, Rajasthan",
        'verified' : true, 
    },
    {
        'id' : '6',
        'entityName' : "Apollo Hospital",
        'requirementName' : "Oxygen",
        'primaryContact' : '+91 XXXXXXXXXX',
        'secondaryContact' : '+91 XXXXXXXXXX',
        'location' : "Jaipur, Rajasthan",
        'verified' : true, 
    },
    {
        'id' : '7',
        'entityName' : "Apollo Hospital",
        'requirementName' : "Oxygen",
        'primaryContact' : '+91 XXXXXXXXXX',
        'secondaryContact' : '+91 XXXXXXXXXX',
        'location' : "Jaipur, Rajasthan",
        'verified' : false, 
    },
    {
        'id' : '8',
        'entityName' : "Apollo Hospital",
        'requirementName' : "Oxygen",
        'primaryContact' : '+91 XXXXXXXXXX',
        'secondaryContact' : '+91 XXXXXXXXXX',
        'location' : "Jaipur, Rajasthan",
        'verified' : true, 
    }
];

export default requirementData;