const hospitalRequirementData = [
    {
        'id' : '1',
        'entityName' : "Apollo Hospital",
        'primaryContact' : '+91 XXXXXXXXXX',
        'secondaryContact' : '+91 XXXXXXXXXX',
        'location' : "Jaipur, Rajasthan",
        'icu': '24',
        'normal': '48',
        'verified' : true,
    },
    {
        'id' : '1',
        'entityName' : "Apollo Hospital",
        'primaryContact' : '+91 XXXXXXXXXX',
        'secondaryContact' : '+91 XXXXXXXXXX',
        'location' : "Jaipur, Rajasthan",
        'icu': '0',
        'normal': '12',
        'verified' : false,
    },
    {
        'id' : '1',
        'entityName' : "Apollo Hospital",
        'primaryContact' : '+91 XXXXXXXXXX',
        'secondaryContact' : '+91 XXXXXXXXXX',
        'location' : "Jaipur, Rajasthan",
        'icu': '04',
        'normal': '08',
        'verified' : true,
    },
    {
        'id' : '1',
        'entityName' : "Apollo Hospital",
        'primaryContact' : '+91 XXXXXXXXXX',
        'secondaryContact' : '+91 XXXXXXXXXX',
        'location' : "Jaipur, Rajasthan",
        'icu': '98',
        'normal': '121',
        'verified' : true,
    },
    {
        'id' : '1',
        'entityName' : "Apollo Hospital",
        'primaryContact' : '+91 XXXXXXXXXX',
        'secondaryContact' : '+91 XXXXXXXXXX',
        'location' : "Jaipur, Rajasthan",
        'icu': '24',
        'normal': '48',
        'verified' : true,
    },
    {
        'id' : '1',
        'entityName' : "Apollo Hospital",
        'primaryContact' : '+91 XXXXXXXXXX',
        'secondaryContact' : '+91 XXXXXXXXXX',
        'location' : "Jaipur, Rajasthan",
        'icu': '24',
        'normal': '48',
        'verified' : true,
    },
    {
        'id' : '1',
        'entityName' : "Apollo Hospital",
        'primaryContact' : '+91 XXXXXXXXXX',
        'secondaryContact' : '+91 XXXXXXXXXX',
        'location' : "Jaipur, Rajasthan",
        'icu': '24',
        'normal': '48',
        'verified' : true,
    },
    {
        'id' : '1',
        'entityName' : "Apollo Hospital",
        'primaryContact' : '+91 XXXXXXXXXX',
        'secondaryContact' : '+91 XXXXXXXXXX',
        'location' : "Jaipur, Rajasthan",
        'icu': '24',
        'normal': '48',
        'verified' : true,
    },
];

export default hospitalRequirementData;